import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* הוספתי פה relative כדי שהאלמנטים הצפים יתיישרו לפי המסך */}
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
          
          {/* הנה התיקון: Header צף (absolute) בצד שמאל למעלה, לא תופס מקום בכלל */}
          <header className="absolute top-10 left-10 z-50">
            <SignedIn>
              <UserButton appearance={{ elements: { userButtonAvatarBox: "w-10 h-10" } }} />
            </SignedIn>
          </header>
          
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}